<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.10.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest" Version="3.11.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SonyControl.Presentation\SonyControl.Presentation.csproj" />
  </ItemGroup>

</Project>
